"""
OpenKeywords - SE Ranking Gap Analysis Example

SE Ranking finds keywords your competitors rank for but you don't,
filtered for AEO (Answer Engine Optimization) potential.

Before running, set your API keys:
    export GEMINI_API_KEY='your-gemini-api-key'
    export SERANKING_API_KEY='your-seranking-api-key'

Run from project root:
    python examples/with_seranking.py
"""

import asyncio
import os

from openkeywords import KeywordGenerator, CompanyInfo, GenerationConfig


async def main():
    # Check API keys
    if not os.getenv("GEMINI_API_KEY"):
        print("Error: Set GEMINI_API_KEY environment variable")
        return

    has_seranking = bool(os.getenv("SERANKING_API_KEY"))
    if not has_seranking:
        print("Note: SERANKING_API_KEY not set - gap analysis will be skipped")
        print("Keywords will be generated by AI only.\n")

    # Initialize generator (picks up API keys from env vars)
    generator = KeywordGenerator()

    # Define company with URL (required for gap analysis)
    company = CompanyInfo(
        name="FitnessPro",
        url="https://fitnesspro.com",  # Required for gap analysis!
        industry="Health & Fitness",
        description="Online fitness coaching and workout programs",
        services=["personal training", "nutrition coaching", "workout plans"],
        products=["FitnessPro App", "Meal Plans"],
        target_audience="health-conscious adults",
        target_location="United States",
        # Optional: specify competitors (auto-detected if not provided)
        competitors=["myfitnesspal.com", "noom.com"],
    )

    # Configure generation
    config = GenerationConfig(
        target_count=50,
        min_score=40,
        enable_clustering=True,
        cluster_count=6,
        language="english",
        region="us",
    )

    print(f"\n🔑 Generating keywords for {company.name}...")
    print(f"   URL: {company.url}")
    print(f"   SE Ranking gap analysis: {'enabled' if has_seranking else 'disabled'}")
    if company.competitors:
        print(f"   Competitors: {', '.join(company.competitors)}")
    print()

    # Generate keywords
    # If SE Ranking is configured, this will:
    # 1. Run gap analysis to find competitor keywords
    # 2. Generate AI keywords to fill gaps
    # 3. Combine, score, deduplicate, and cluster
    result = await generator.generate(company, config)

    print(f"✓ Generated {len(result.keywords)} keywords in {result.processing_time_seconds:.1f}s")
    print(f"  Average score: {result.statistics.avg_score:.1f}")
    print(f"  Duplicates removed: {result.statistics.duplicate_count}")

    # Display with volume/difficulty data (populated by SE Ranking)
    print("\n📝 Top Keywords with Metrics:")
    print("-" * 100)
    print(f"{'Keyword':<45} | {'Intent':<12} | {'Score':>5} | {'Volume':>7} | {'Difficulty':>4}")
    print("-" * 100)

    for kw in result.keywords[:15]:
        print(
            f"{kw.keyword:<45} | {kw.intent:<12} | {kw.score:>5} | {kw.volume:>7} | {kw.difficulty:>4}"
        )

    # Sort by volume (meaningful if SE Ranking provided data)
    keywords_with_volume = [kw for kw in result.keywords if kw.volume > 0]
    if keywords_with_volume:
        by_volume = sorted(keywords_with_volume, key=lambda x: x.volume, reverse=True)
        print("\n📈 Top 10 by Search Volume (from SE Ranking):")
        print("-" * 70)
        for kw in by_volume[:10]:
            print(f"  {kw.keyword:<45} | Volume: {kw.volume:>6}")

    # Question keywords (AEO optimized)
    questions = [kw for kw in result.keywords if kw.is_question or kw.intent == "question"]
    if questions:
        print(f"\n❓ Question Keywords ({len(questions)} - great for AEO):")
        print("-" * 70)
        for kw in questions[:10]:
            print(f"  {kw.keyword}")

    # Export
    result.to_csv("keywords_with_gaps.csv")
    result.to_json("keywords_with_gaps.json")
    print("\n✓ Exported to keywords_with_gaps.csv and keywords_with_gaps.json")


if __name__ == "__main__":
    asyncio.run(main())
